In [1]:
# data handling package - pandas

import pandas as pd

In [2]:
# table data - dataframe
df = pd.read_csv('data/student_performance_500.csv')

In [3]:
df

,student_id,gender,math_score,reading_score,writing_score,parental_education,study_hours,attendance_percentage
0,1,Male,97.0,60.0,NaN,Master,2.0,NaN
1,2,Female,66.0,NaN,81.0,Associate,4.0,68.0
2,3,Male,67.0,44.0,96.0,Bachelor,5.0,95.0
3,4,Male,52.0,58.0,96.0,High School,5.0,81.0
4,5,Male,59.0,98.0,86.0,NaN,2.0,85.0
...,...,...,...,...,...,...,...,...
495,496,Male,45.0,69.0,90.0,Associate,5.0,83.0
496,497,Male,48.0,77.0,61.0,High School,3.0,NaN
497,498,Female,94.0,73.0,97.0,Bachelor,NaN,98.0
498,499,Male,64.0,51.0,NaN,High School,2.0,98.0
499,500,Female,69.0,58.0,40.0,Associate,1.0,72.0

In [5]:
df.describe()

,student_id,math_score,reading_score,writing_score,study_hours,attendance_percentage
count,500.000000,450.000000,450.000000,450.000000,450.000000,450.000000
mean,250.500000,66.493333,70.140000,69.153333,3.055556,79.640000
std,144.481833,19.412787,17.168896,17.847686,1.435791,11.272261
min,1.000000,35.000000,40.000000,38.000000,1.000000,60.000000
25%,125.750000,50.000000,56.000000,53.000000,2.000000,70.000000
50%,250.500000,66.000000,71.000000,69.000000,3.000000,80.000000
75%,375.250000,84.000000,85.000000,84.000000,4.000000,89.000000
max,500.000000,99.000000,99.000000,99.000000,5.000000,99.000000

In [7]:
# df.*?
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             500 non-null    int64
 1   gender                 500 non-null    str
 2   math_score             450 non-null    float64
 3   reading_score          450 non-null    float64
 4   writing_score          450 non-null    float64
 5   parental_education     460 non-null    str
 6   study_hours            450 non-null    float64
 7   attendance_percentage  450 non-null    float64
dtypes: float64(5), int64(1), str(2)
memory usage: 31.4 KB

In [8]:
df.drop_duplicates()

,student_id,gender,math_score,reading_score,writing_score,parental_education,study_hours,attendance_percentage
0,1,Male,97.0,60.0,NaN,Master,2.0,NaN
1,2,Female,66.0,NaN,81.0,Associate,4.0,68.0
2,3,Male,67.0,44.0,96.0,Bachelor,5.0,95.0
3,4,Male,52.0,58.0,96.0,High School,5.0,81.0
4,5,Male,59.0,98.0,86.0,NaN,2.0,85.0
...,...,...,...,...,...,...,...,...
495,496,Male,45.0,69.0,90.0,Associate,5.0,83.0
496,497,Male,48.0,77.0,61.0,High School,3.0,NaN
497,498,Female,94.0,73.0,97.0,Bachelor,NaN,98.0
498,499,Male,64.0,51.0,NaN,High School,2.0,98.0
499,500,Female,69.0,58.0,40.0,Associate,1.0,72.0

In [12]:
df[df.duplicated()]  # to get duplicates
# no duplicates - empty dataframe

Empty DataFrame
Columns: [student_id, gender, math_score, reading_score, writing_score, parental_education, study_hours, attendance_percentage]
Index: []