In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('data/my_data.csv')
df

   id name  mobile course
0   1    a     123     ds
1   2    b     345    cse
2   1    a     123     ds

In [7]:
display(df)

   id name  mobile course
0   1    a     123     ds
1   2    b     345    cse
2   1    a     123     ds

In [8]:
print(df)

   id name  mobile course
0   1    a     123     ds
1   2    b     345    cse
2   1    a     123     ds

In [9]:
df.drop_duplicates()

   id name  mobile course
0   1    a     123     ds
1   2    b     345    cse

In [10]:
df.duplicated()

0    False
1    False
2     True
dtype: bool

In [12]:
df[df.duplicated()]

   id name  mobile course
2   1    a     123     ds

In [14]:
duplicates = df[df.duplicated()]
duplicates

   id name  mobile course
2   1    a     123     ds